### ISSUE TITLE
Docs: confusion about the grammar

### ISSUE THREAD

**Issue by LanceNorskog** [airbnb/mensor#17]
The documentation mentions a 'grammar', but only includes Python code. Is there a separate grammar for defining measures, or is the grammar just Python?

I envision using this from a database of names & measure definitions, possibly with parameterization.
I also envision using this from different programming languages, not just Python, so maybe a YAML format would be useful?

**Comment by matthewwardrop** [comment]
Hi @LanceNorskog . The grammar described in the documentation is the Python API used to evaluate measures and metrics, and the syntax of strings used to traverse the graph that are passed to these methods. The term "grammar" is used somewhat loosely.

Metric and measure definition can be done in Python or YAML as of the latest release :).
