### ISSUE TITLE
Hive does not allow \ in column names 

### ISSUE THREAD

**Issue by danfrankj** [airbnb/mensor#7]
Some SQL dialects e.g. Hive will not allow `\` as a column identifier

```
hive> SELECT 1 AS `foobar/baz`;
FAILED: ParseException line 1:12 rule Identifier failed predicate: {allowQuotedId()}?
```

**Comment by matthewwardrop** [comment]
Yeah... I predicted that might be an issue. The solution? I think just a method that is dialect specific that converts mensor style field-names into appropriately quoted columns identifiers, and then just the inverse mapping after running the query in the evaluate method.

Thoughts?

**Comment by matthewwardrop** [comment]
Fixed in master! Thanks @danfrankj
